### ISSUE TITLE
Nether and Lava fog seem to not be toggleable while using sodium.

### ISSUE THREAD

**Issue by SpookLad** [Virtuoel/NoFog#1]
This mod has incompatibilities with sodium, making it not function with denser fog. The overworld fog seems to still be toggleable, however.

**Comment by Tommeh1** [comment]
Please provide your sodium version

**Comment by Spatonn** [comment]
This happens to me too, the sodium version I use is 0.4.0 alpha5

**Comment by Spatonn** [comment]
will this ever be fixed?

**Comment by LogicalGeekBoy** [comment]
This is the case for all fog as far as I can see in 1.18.2 and Sodium 0.4.1 (build.15). I believe Sodium have added a way for mods to control the fog now. Would it be possible to support Sodium at some point?

**Comment by SpookLass** [comment]
This seems to have been fixed, and the mod now works with sodium.

**Comment by SpookLad** [comment]
Little8man is me btw, not sure how I ended up with a new account.
