### ISSUE TITLE
NoFog does not work underground

### ISSUE THREAD

**Issue by mapyDayton22** [Virtuoel/NoFog#12]
I go underground near bedrock, I still fog

**Comment by Tommeh1** [comment]
NoFog Version?

**Comment by Virtuoel** [comment]
Unable to reproduce this with the latest NoFog version.
Lack of versions, mod list, Minecraft version, etc. make it hard to know what sort of situation made your problem happen.

If you still have this problem with the newest NoFog for your Minecraft version, please open a new issue and include more information.
