### ISSUE TITLE
[Suggestion]: no fog mod for 1.19.3?

### ISSUE THREAD

**Issue by CrippleKitten** [Virtuoel/NoFog#14]
### What is your suggestion?

Hiya,
Due to MC Realms updating to 1.19.3 the no fog mod no longer works for me. Is there a possibility of a 1.19.3 version coming out soon?

**Comment by Tommeh1** [comment]
I'm currently testing the existing builds, the 1.16.5-1.19.2 Fabric build seems to work for 1.19.3 without any dependencies, but indeed doesn't disable any fog or provide config options when the optional dependencies are present: 
[latest.log](https://github.com/Virtuoel/NoFog/files/10229869/latest.log)
The 1.16.5-1.19.2 Forge build however even crashes without any dependencies on 1.19.3: 
[crash-2022-12-14_17.59.22-client.txt](https://github.com/Virtuoel/NoFog/files/10230035/crash-2022-12-14_17.59.22-client.txt)

**Comment by Virtuoel** [comment]
The 1.3.2 release is now out with support for 1.19.3. Currently available on [Modrinth](https://modrinth.com/mod/no_fog/versions) and [GitHub Releases](https://github.com/Virtuoel/NoFog/releases) (still waiting on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/nofog/files/all) to approve)
