### ISSUE TITLE
[Suggestion]: License on CurseForge

### ISSUE THREAD

**Issue by iambeingtracked** [Virtuoel/NoFog#15]
### What is your suggestion?

The [Curseforge page](https://www.curseforge.com/minecraft/mc-mods/nofog) lists the license as "All Rights Reserved", however the license here is MIT.

Please change the license on the Curseforge page to match what's on GitHub.

**Comment by Tommeh1** [comment]
I prefer to keep the project itself locked behind All Rights Reserved to more easily be able to deal with other websites rehosting my mod without permission.
I'm well aware that some other licenses also cover this, but with All Rights Reserved there is no way this can raise any kind of discussion or poor excuse.

Besides that i see no use in having another license on the project itself anyways as i already explicitly state that one is free to use it in any modpack.

**Comment by iambeingtracked** [comment]
But what about the source? It is licensed under MIT, so the mod should also be MIT

**Comment by Tommeh1** [comment]
> But what about the source? It is licensed under MIT, so the mod should also be MIT

I believe that the Curse license more so applies to the project itself rather than the code, allowing it to differ without problems.

**Comment by iambeingtracked** [comment]
Reasonable, the source and the binaries may be licensed with different licenses. However, if there is no malicious intent, what's wrong with rehosting a mod? It's basically just copying the mod's binary to an another place

**Comment by Tommeh1** [comment]
> Reasonable, the source and the binaries may be licensed with different licenses. However, if there is no malicious intent, what's wrong with rehosting a mod? It's basically just copying the mod's binary to an another place

They steal downloads from the true source and allows the rehosting sites to profit off of someone else their code.
And although most aren't otherwise malicious some are injected with malicious code.

**Comment by iambeingtracked** [comment]
But if someone wants to make it malicious, they will just do it without asking for your permission, same with "rehosting sites", they can just post the links to your things and still have loads of ads on that page, although it doesn't break any of those "rules".

In this case I think it's better to have everything freely redistributable.

**Comment by Tommeh1** [comment]
> But if someone wants to make it malicious, they will just do it without asking for your permission, same with "rehosting sites", they can just post the links to your things and still have loads of ads on that page, although it doesn't break any of those "rules".
> 
> In this case I think it's better to have everything freely redistributable.

At least they won't be able to bring up poor excuses and try and bend the license in their favor or whatever.
And i'm not sure what rules you're referring to, but i clearly state that reposting it is not allowed, no matter what.
