### ISSUE TITLE
[Bug]: Trojan found in NoFog-1.2.1-1.18.2 inside the Ars Noveau Server Modpack

### ISSUE THREAD

**Issue by KeoPlays** [Virtuoel/NoFog#17]
### Minecraft version(s)

1.18.2

### Mod loader

Forge

### Mod loader version

CurseForge?

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

While installing the modpack my Bitdefender Premium gave out a warning message for a trojan with the name of Java.Trojan.GenericGBA.31501 with a serious thread level. It was found inside of the jar file. 
![image](https://user-images.githubusercontent.com/124216100/216191398-797c770c-fd64-41d0-a20d-a97e9fc502fa.png)

### Full list of installed mods and their version numbers

I dont have hours to type here have a modlist from curseforge
https://www.curseforge.com/minecraft/modpacks/ars-nouveau-discord-server/relations/dependencies

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by KeoPlays** [comment]
I did run it through virustotal which also found the trojan. I might not be an expert when it comes to coding things or bug stuff but i thought i might be helpful and report it to ya. ^^

**Comment by Virtuoel** [comment]
This was a false positive that got resolved with the newer NoFog versions like `NoFog-1.3.2_1.18.2-forge.jar`.
