### ISSUE TITLE
Game crashing in mod menu when trying to expand settings

### ISSUE THREAD

**Issue by Zanteri** [Virtuoel/NoFog#18]
Whenever I open the settings in Mod Menu, the game crashed when trying to expand any of the three categories. I have the required mods listed on the page. I'm also going to attach the crash report here. Let me know if there's anything else to add, thanks.
[crash-2023-03-03_11.08.42-client.txt](https://github.com/Virtuoel/NoFog/files/10884625/crash-2023-03-03_11.08.42-client.txt)

**Comment by Virtuoel** [comment]
Your Cloth Config is slightly out of date, using version 9.0.93. Does the crash still happen for you if you update it to 9.0.94?

**Comment by Virtuoel** [comment]
Closing due to lack of response. If this crash still occurs for you after updating Cloth Config, please leave a comment with the new crash log.
