### ISSUE TITLE
[Version bump]: 1.19.4

### ISSUE THREAD

**Issue by Loatchi** [Virtuoel/NoFog#19]
### What is your suggestion?

I runned Nofog with the fabric launcher in 1.19.4 and for now it seems to work properly. 
The only thing missing is the ModMenu. 

For anyone wondering, you can use the mod from 1.19.3 in 1.19.4 .

I havent test it for forge.

Thanks for your work !
Loatchi

**Comment by Virtuoel** [comment]
1.19.4 versions have been released on Modrinth and GitHub Releases. CurseForge versions shall be released shortly.
