### ISSUE TITLE
[Bug]: Opening config will cause crash on 1.16.5

### ISSUE THREAD

**Issue by ghost** [Virtuoel/NoFog#20]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

36.2.39

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Opening config will cause crash on 1.16.5

### Full list of installed mods and their version numbers

dynamiclightsreforged-mc1.16.5_v1.0.1.jar, randomloot-1.16.5-2.3.9.jar, TRansliterationLib-1.0.4.jar, rubidium-0.2.11.jar, XaerosWorldMap_1.29.4_Forge_1.16.5.jar, Controlling-7.0.0.29.jar, Prism-1.16.5-1.0.1.jar, Placebo-1.16.5-4.7.0.jar, citadel-1.8.1-1.16.5.jar, alexsmobs-1.12.1.jar, ImprovedBackpacks-1.6.2.1.jar, Bookshelf-Forge-1.16.5-10.4.33.jar, Tips-1.16.5-4.0.18.jar, sophisticatedbackpacks-1.16.5-3.15.20.755.jar, lootbeams-1.16.5-release-july1722.jar, guardvillagers-1.16.5.1.2.6.jar, Apotheosis-1.16.5-4.8.9A0.jar, PickUpNotifier-v1.2-1.16.3.jar, carryon-1.16.5-1.15.5.22.jar, dummmmmmy-1.16.5-1.3.2.jar, twilightforest-1.16.5-4.0.870-universal.jar, refinedstorage-1.9.18.jar, EquipmentCompare-1.16.5-1.3.2.jar, corpse-1.16.5-1.0.6.jar, EventsLootbags-1.16.5-1.0.1.jar, BiomesOPlenty-1.16.5-13.1.0.477-universal.jar, spark-1.9.1-forge.jar, oculus-1.4.5.jar, collective-1.16.5-5.49.jar, OreExcavation-1.8.157.jar, starterkit_1.16.5-4.1.jar, eatinganimation-1.16.5-1.0.0.jar, cc-tweaked-1.16.5-1.101.2.jar, ItemPhysic_v1.4.18_mc1.16.5.jar, cloth-config-4.16.91-forge.jar, TrampleStopper-2.6.1-build.22+mc1.16.5.jar, smallernetherportals_1.16.5-1.7.jar, GameMenuModOption-1.16.4-1.8.2.jar, treasure-bags-1.16.3-1.4.0.jar, TrashSlot_1.16.3-12.2.1.jar, XPFromHarvest-1.16.5-1.2.2.jar, treeharvester_1.16.5-5.9.jar, jei-1.16.5-7.8.0.1009.jar, randomtp-4.4.0+1.16-forge.jar, Mekanism-1.16.5-10.1.2.457.jar, PassableFoliage-1.16.5-2.4.0.jar, MerchantMarkers-1.16.5-1.3.0.jar, shutupexperimentalsettings-1.0.3.jar, appliedenergistics2-8.4.7.jar, tumbleweed-1.16-0.4.9.jar, TravelersBackpack-1.16.5-5.4.33.jar, SereneSeasons-1.16.5-4.0.1.129-universal.jar, configured-1.5.3-1.16.5.jar, BasicNetherOres-1.16.5-5.5.0.jar, autoattack-1.16.5-1.0.jar, DungeonCrawl-1.16.5-2.3.12.jar, StepUp-1.16.4-0.2.0.jar, catalogue-1.6.1-1.16.5.jar, walljump-forge-1.16.4-1.3.7.jar, ToastControl-1.16.5-4.4.0.jar, magnesium_extras-mc1.16.5_v1.4.0.jar, wandering-bag-1.16.5-1.0.4.jar, forge-1.16.5-36.2.39-universal.jar, Bountiful-1.16.4-3.3.1.jar, DynamicSurroundings-1.16.5-4.0.5.0.jar, LootBag-1.16.5-1.2.2.jar, ironchest-1.16.5-11.2.21.jar, NoFog-1.3.2_1.16.5-forge.jar, cofh_core-1.16.5-1.5.2.22.jar, thermal_foundation-1.16.5-1.5.2.30.jar, thermal_expansion-1.16.5-1.5.2.16.jar, TConstruct-1.16.5-3.3.4.335.jar, MouseTweaks-2.14-mc1.16.2.jar, ImmersiveEngineering-1.16.5-5.1.0-148.jar, silent-lib-1.16.3-4.9.6.jar, Jade-1.16.4-2.8.3.jar, ShoulderSurfing-Forge-1.16.5-2.3.0.jar, FirstPersonMod-2.0.1.jar, CreativeCore_v2.2.1_mc1.16.5.jar, smoothboot-forge-1.16.4-1.2.2.jar, Ding-1.16.5-1.3.0.jar, notenoughanimations-1.2.4.jar, Iceberg-1.16.5-1.0.45.jar, flywheel-1.16-0.2.5.jar, create-mc1.16.5_v0.3.2g.jar, automaticdoors_1.16.5-2.4.jar, Mantle-1.16.5-1.6.157.jar, LegendaryTooltips-1.16.5-1.3.1.jar, Xaeros_Minimap_23.3.2_Forge_1.16.5.jar, seasonhud-1.16.5-1.4.8.jar, Croptopia-1.16.5-FORGE-2.0.5.jar, StorageDrawers-1.16.3-8.5.2.jar, backpacked-2.1.8-1.16.5.jar, appleskin-forge-mc1.16.x-2.4.0.jar, Infinitylib-2.0.7.jar, agricraft-3.0.8.jar, ferritecore-2.1.1-forge.jar, enhancedcelestials-2.0.9-1.16.5.jar, BetterF3-1.5.0-Forge-1.16.5.jar, SoundFilters-0.14_for_1.16.2.jar, xptome-1.16.5-v2.1.5.jar, villagernames_1.16.5-4.3.jar, AdvancementPlaques-1.16.5-1.4.1.jar, villagespawnpoint_1.16.5-3.0.jar, architectury-1.32.66.jar, betteranimalmodels-1.16.5-5.6.0-forge.jar, [1.16.5]-Epic-Knights-7.12.jar, betteranimalsplus-1.16.5-11.0.10-forge.jar, environmentalcreepers-forge-1.16.3-1.6.0.jar, iChunUtil-1.16.5-10.7.0.jar, supermartijn642configlib-1.1.6-forge-mc1.16.jar, durabilitytooltip-1.1.4-forge-mc1.16.jar, instantunify-1.16.4-1.0.0.jar, corail_recycler-1.16.5-5.2.0.jar, responsiveshields-2.1-mc1.16.5.jar, WellBehavedMobs-v1.2.3-1.16.5.jar, swingthroughgrass-1.16.4-1.5.3.jar, curios-forge-1.16.5-4.1.0.0.jar, curioofundying-forge-1.16.5-5.2.0.0.jar, lazydfu-0.1.3.jar, [1.16.5] BobLib-0.2.0.jar, [1.16.5] SimpleHomes-1.1.0.jar, sapience-1.16.5-1.1.2.jar, VisualWorkbench-v1.1.0-1.16.5.jar, AttributeFix-1.16.5-10.1.4.jar, memoryleakfix-forge-pre1.17-1.0.0-beta.6.jar, PuzzlesLib-v1.0.15-1.16.5-Forge.jar, inventorysorter-1.16.1-18.1.0.jar

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

[crash-2023-03-27_06.41.08-client.txt](https://github.com/Virtuoel/NoFog/files/11081904/crash-2023-03-27_06.41.08-client.txt)
[latest.log](https://github.com/Virtuoel/NoFog/files/11081905/latest.log)

**Comment by Virtuoel** [comment]
Not a NoFog problem.
Appears to be caused by TRansliterationLib shadowing an outdated version of Cloth Config which seems to be taking priority over the newer Cloth Config version that's in the mods folder.

**Comment by ghost** [comment]
How did you found out it?
