### ISSUE TITLE
[Bug]: Not working on 1.19.3?

### ISSUE THREAD

**Issue by rustedgoldmc** [Virtuoel/NoFog#22]
### Minecraft version(s)

Other (specify below)

### Minecraft version details

1.19.3

### Mod loader

Fabric

### Mod loader version

The latest one as of May 1

### Fabric API version

Fabric API 0.76.1

### In what kind of world or server did the problem occur?

A multiplayer server that I was connected to

### What went wrong? (Crash logs don't go here)

I was trying to remove nether fog. Installed the mod into my modpack, and it didn't work. My friend tried as well, and it didn't work for him either. Didn't hurt anything, showed up in ModMenu and all, just did nothing.

### Full list of installed mods and their version numbers

This is the link to the .zip folder all the server's mods are in. https://drive.google.com/file/d/1p4DLbxk6yMU2-yZDxdOnmyLbEwgT-A0A/view?usp=share_link

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by TimDev9492** [comment]
I'm on Minecraft version 1.19.2 and for me, it only works in the overworld. In the nether and the end, the fog shows up, even if I turn it off.

**Comment by Tommeh1** [comment]
If i'm not mistaken better nether, just like better end has their own fog configs since a previous issue(#3) related to them.

**Comment by Virtuoel** [comment]
As mentioned above, BetterNether and BetterEnd use BCLib for their custom fog. Check the BCLib config to disable their custom fog.
