### ISSUE TITLE
[Bug]: Can't configurate with Modmenu and ClothConfig in fabric

### ISSUE THREAD

**Issue by franbani** [Virtuoel/NoFog#24]
### Minecraft version(s)

1.19.4

### Mod loader

Fabric

### Mod loader version

0.14.19

### Fabric API version

0.80.0

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

what the title says, you can't configurate it in the config menu, like, it doesn't give you the option like with other configurable mods

### Full list of installed mods and their version numbers

sodium-fabric-mc1.19.4-0.4.10+build.24
NoFog-1.3.3_1.16.5-1.19.4-fabric
modmenu-6.2.2
logical_zoom-0.0.19
lambdynamiclights-2.3.0+1.19.4
fabric-api-0.80.0+1.19.4
cloth-config-10.0.96-forge

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Tommeh1** [comment]
If your mods list is correct you installed the forge build of cloth config instead of the fabric one

**Comment by franbani** [comment]
oh that's true, my bad
