### ISSUE TITLE
[Suggestion]: 1.20 Support

### ISSUE THREAD

**Issue by 42willow** [Virtuoel/NoFog#25]

**Comment by Athar42** [comment]
This mod is so usefull, any idea on an ETA on this or not at all ? (will be done when it will ? 😂)

**Comment by Fabian42** [comment]
Just yesterday I learned that "Sodium extra" also lets you do this (and more) and it's updated to 1.20.

**Comment by Virtuoel** [comment]
Resolved as of the 1.3.4 release, which is out on Modrinth. Curseforge upload is still processing and will be out soon.
