### ISSUE TITLE
[Bug]: Untitled bug report

### ISSUE THREAD

**Issue by dophire** [Virtuoel/NoFog#27]
### Minecraft version(s)

1.20.1

### Mod loader

Quilt

### Mod loader version

Quilt Loader 0.19.2 

### Fabric API version

Fabric API 0.84

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

In the NoFog mod, in the Dimension Type Settings, the minecraft:overworld_caves option doesn't work properly. My goal is to have the fog in the caves, but not on the surface. The biome selective fog for cave types such as the dripstone, lush, and deep dark caves work as intended. However, despite having sky, terrain, and thick fog options enabled in the minecraft:overworld_caves, the fog still does not show up while being in a cave.
Expected behavior - fog in all caves, but not on the surface of the overworld.

![2023-07-23_03 11 17](https://github.com/Virtuoel/NoFog/assets/38838633/5a74fb28-897f-4e1d-9b3f-319437028276)
![2023-07-23_03 11 24](https://github.com/Virtuoel/NoFog/assets/38838633/af037a0d-5a22-4a27-8bd3-d949f0498721)
![2023-07-23_03 29 27](https://github.com/Virtuoel/NoFog/assets/38838633/1dcfe9be-138a-4f81-b4a9-7d0e118eab83)
![2023-07-23_03 29 38](https://github.com/Virtuoel/NoFog/assets/38838633/5a18df76-f850-4e92-80d2-f27d2f0efc6e)

### Full list of installed mods and their version numbers

![Screenshot 2023-07-23 032342](https://github.com/Virtuoel/NoFog/assets/38838633/42f57656-ca8e-4769-bd33-20e4cf2c09cc)

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Tommeh1** [comment]
Have you tried reproducing the issue with only NoFog and its (optional) dependencies installed?

**Comment by Virtuoel** [comment]
`overworld_caves` is a dimension type that is unused in vanilla. It still is something that exists though, so it'll show up in the config.

It has nothing to do with whether you're in a cave or not. I think it's like, a thing for worldgen/dimension datapack makers?

Either way, since it's not used by anything, changing it will not affect fog.

**Comment by dophire** [comment]
So there's no way to make fog appear exclusively in caves? What about adding a Y-coordinate option to the mod, so that if you're below let's say, the Y-level of 40, fog will render?
