### ISSUE TITLE
[Bug]: Not working with newest Sodium

### ISSUE THREAD

**Issue by achhandrian** [Virtuoel/NoFog#29]
### Minecraft version(s)

1.20.1

### Minecraft version details

1.20.1

### Mod loader

Fabric

### Mod loader version

fabric-loader-0.14.21-1.20.1

### Fabric API version

fabric-api-0.86.1+1.20.1

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

NoFog doesnt work with the last Sodium update, there is no crash but the rendering is totally strange.
It only renders one Chunk at best, sometime not even the full chunk.

would be nice if the compability between the two mods could be fixed.

![Bild_2023-08-14_103757975](https://github.com/Virtuoel/NoFog/assets/74990775/0e494724-b0b7-4596-930d-7a881217dbb7)

### Full list of installed mods and their version numbers

fabric-api-0.86.1+1.20.1.jar
NoFog-1.3.4_1.16.5-1.20.1-fabric.jar
sodium-fabric-mc1.20.1-0.5.1.jar

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by NotDarkn** [comment]
happens for me as well on Sodium 0.5.1

**Comment by itsarian** [comment]
can confirm

**Comment by FlashyReese** [comment]
This is a bug caused by Sodium. You need to wait for them to release the fix.
![image](https://github.com/Virtuoel/NoFog/assets/30311066/b84b7c4a-6c5a-4a3e-af28-1d4996223de0)

**Comment by itsarian** [comment]
> 

well thats a bummer

**Comment by korren84** [comment]
Bug for Sodium 0.5.1 can be worked around if you disable Use Fog Occlusion under performance and the chunks will render.

**Comment by 42willow** [comment]
o.o I just spent 10 minutes sifting through my mods to find the source. 

> Bug for Sodium 0.5.1 can be worked around if you disable Use Fog Occlusion under performance and the chunks will render.

o.o I just spent 10 minutes trying to figure out which plugin was causing the problem (as I updated all of them)

ty

**Comment by iblowmymind** [comment]
Can someone test if it works with Sodium 0.5.2?

**Comment by achhandrian** [comment]
> Can someone test if it works with Sodium 0.5.2?

it does work yes.

**Comment by achhandrian** [comment]
After the sodium update 0.5.2. problem is fixed.

**Comment by ST-DDT** [comment]
Tested with:

````txt
indium-1.0.25+mc1.20.1.jar
sodium-fabric-mc1.20.1-0.5.2.jar
iris-mc1.20.1-1.6.8.jar
NoFog-1.3.4_1.16.5-1.20.1-fabric.jar
````

Works as expected

**Comment by iblowmymind** [comment]
Alright, thanks! I suppose this issue can be closed, then.
