### ISSUE TITLE
Cannot disable fog in custom dimension mods such as Better Nether and Better end

### ISSUE THREAD

**Issue by KB-Q** [Virtuoel/NoFog#3]
Like the title said, the fog in mods such as Better Nether and Better end which generate custom terrain and biomes is still there even after disabling all fog in the No Fog configs. Please see the attached screenshots for reference. 
Game version 1.18.1 (Fabric), using the latest version of the No Fog mod.

![2022-02-05_17 18 14](https://user-images.githubusercontent.com/59303688/152641045-972a4f34-bab3-4348-9c7a-47c0805e2abf.png)
(Better End 1.18.1)

![2022-02-05_17 24 59](https://user-images.githubusercontent.com/59303688/152641063-00ffaa49-3760-4f5a-af94-3b4fe7a709d4.png)
(Better Nether 1.18.1)

**Comment by Tommeh1** [comment]
For reference: https://github.com/paulevsGitch/BCLib/issues/74

**Comment by SpookLass** [comment]
You can fix this by turning off custom fog in the config. (That worked for LOD's disable fog feature anyway)

**Comment by Virtuoel** [comment]
Resolved on BCLib's end with their fog config as previously mentioned above.
