### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zc1108aaa** [Virtuoel/NoFog#33]
### Minecraft version(s)

1.20.1

### Minecraft version details

1

### Mod loader

Fabric

### Mod loader version

0.15.11

### Fabric API version

0.92.2+1.20.1

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

[latest.log](https://github.com/user-attachments/files/15532708/latest.log)

### Full list of installed mods and their version numbers

[crash-2024-06-03_18.35.27-client.txt](https://github.com/user-attachments/files/15532711/crash-2024-06-03_18.35.27-client.txt)

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Looking at your latest.log, seems your crash is not related to NoFog but is actually related to some of your Farmers Delight addons not being compatible with Farmers Delight Refabricated.
