### ISSUE TITLE
NoFog doesn't work in 1.18.2

### ISSUE THREAD

**Issue by KB-Q** [Virtuoel/NoFog#6]
The 1.18.2 version of the mod (NoFog-1.16.5-1.18.2-Fabric, downloaded from curseforge) doesn't work. I have clothconfig modmenu and fabricapi installed, and all the global settings set as disabled. However, the fog is still present.

**Comment by Tommeh1** [comment]
Please provide the versions of all installed mods.

**Comment by KB-Q** [comment]
[MC modlist - 1.18.2 15-03-22.txt](https://github.com/Virtuoel/NoFog/files/8301411/MC.modlist.-.1.18.2.15-03-22.txt)

**Comment by KB-Q** [comment]
Any update?

**Comment by Drunknbyte** [comment]
For me,  it says its not compatible with "optifabric".

![image](https://user-images.githubusercontent.com/83468615/160287069-d2a6ce7e-e6f8-42bf-883a-891368386c08.png)

**Comment by Tommeh1** [comment]
> Any update?

I've tested with the exact mods and their corresponding version from the list you provided but fail to reproduce any issues.

**Comment by Tommeh1** [comment]
> For me, it says its not compatible with "optifabric".
> 
> ![image](https://user-images.githubusercontent.com/83468615/160287069-d2a6ce7e-e6f8-42bf-883a-891368386c08.png)

OptiFabric has decided to mark NoFog as incompatible rather than disabling their own fog options when NoFog is present.
Although as they don't maintain Optifine idk if they've got any way of doing so, so don't immediately complain at them for this.

**Comment by Drunknbyte** [comment]
> > For me, it says its not compatible with "optifabric".
> > ![image](https://user-images.githubusercontent.com/83468615/160287069-d2a6ce7e-e6f8-42bf-883a-891368386c08.png)
> 
> OptiFabric has decided to mark NoFog as incompatible rather than disabling their own fog options when NoFog is present. Although as they don't maintain Optifine idk if they've got any way of doing so, so don't immediately complain at them for this.

Thnks @Tommeh1 !

**Comment by KB-Q** [comment]
> > Any update?
> 
> I've tested with the exact mods and their corresponding version from the list you provided but fail to reproduce any issues.

Hi, I found out it was caused due to the sodium-extras mod, which had it's own option for Fog. I removed it and No Fog works fine now. But anyways thanks for your time.

**Comment by Tommeh1** [comment]
That's odd as i tested with the specific version you were using and everything worked fine, but i'll ask Reese(Sodium Extra dev) to take a look either way.
(EDIT: i infact managed to get the fog stuck disabled, Reese is however working on a PR that should fix this)

**Comment by Tommeh1** [comment]
A new release containing a fix for this is awaiting approval from curse and should be available soon.
