### ISSUE TITLE
Fog disable not working in nether

### ISSUE THREAD

**Issue by uhhams** [Virtuoel/NoFog#8]
im using fabric 1.18.2 and im using the incendium mod for world gen in the nether. ive set all the nether biomes to false and still doesnt seem to work, any fix? (including all the mods I use
![2022-04-27_20 00 40](https://user-images.githubusercontent.com/96365922/165668354-1ed4c12e-2d42-4ef0-b945-b78202b12acd.png)
<img width="2002" alt="Screen Shot 2022-04-27 at 8 04 48 PM" src="https://user-images.githubusercontent.com/96365922/165668566-17992c7e-f20e-4756-8e1b-f20f9f82f11f.png">
)

**Comment by SpookLass** [comment]
BClib might be causing it. I'm not sure why it's in there either, you have no mods that depend on it.

**Comment by uhhams** [comment]
worked, thanks!
